### ISSUE TITLE
API docs appear to be out of date / inaccurate?

### ISSUE THREAD

**Issue by JoshMcCullough** [ngageoint/mage-server#49]
Haven't looked into this too much yet, honestly, just trying to work through it and get to the end of my task. 

It appears that the API docs (/api/swagger) are out of date. Things I've noticed:

- missing (new?) auth endpoints, e.g. `auth/local/signin`, `auth/local/authorize`
- incorrect return type for `api/users/{id}`, e.g. docs indicate far, far smaller payload than what's actually returned

Do I need to re-gen the docs? I assumed they would be auto-gen'd at startup/build time?

**Comment by restjohn** [comment]
The [Swagger doc](https://github.com/ngageoint/mage-server/blob/master/docs/swagger.json) is out of sync with the server's Express routes.  This should hopefully be fixed in the not-too-distant future, without being able to put a concrete estimate on it, by updating to OpenAPI 3 YAML.  It's on the road map.  Pull requests are welcome if you want to take a shot at it.

**Comment by newmanw** [comment]
Although we are moving towards OpenAPI 3 soon, it would be nice to fix the current docs.  I will update the auth routes and fix the api/users return payload.  Let us know if you see more, and as @restjohn mentioned, pull requests are always welcome and helpful.

**Comment by JoshMcCullough** [comment]
Great, thanks!

**Comment by JoshMcCullough** [comment]
`POST users` and `PUT users` are also out of date regarding the payload they require. E.g. "roleId is a required field" but not shown in the docs.
