### ISSUE TITLE
User active vs. enabled?

### ISSUE THREAD

**Issue by JoshMcCullough** [ngageoint/mage-server#50]
What's the difference between the `active` and `enabled` field on a user? Hope you don't mind me asking questions here. Thanks!

Edit: Specifically, when I try to disable a user I was trying to send false for both fields but the user is still coming back as `active=true` and `enabled=true`. I see the web UI, when disabling a user, is `PUT`ing to `users/{id}` and setting `active=true` and `enabled=false`. I tried to not send `active` at all, and set `enabled` to `false`, but it does not appear to take.

**Comment by newmanw** [comment]
Active is a flag used to indicate if an administrator has activated a the users account.  IE this marks the account as new.  Enabled is a flag used to indicate if an administrator has marked the account as enabled/disabled.  An inactive or disabled user account will not be allowed to authenticate.

**Comment by JoshMcCullough** [comment]
Thanks. I'll have to dig in deeper to see why my user is not being disabled.

**Comment by newmanw** [comment]
No worries.  The server is expecting multipart/form-data as user create/update can contain files for map icon and avatar.  Since multipart/form-data cannot contain boolean values the server is parsing the value as a string. For now pass 'true' or 'false'.  There is no reason the server cannot accept a boolean value when passing application/json.  I have written an internal bug to track this issue.

**Comment by JoshMcCullough** [comment]
Thanks. Got it working.
